"""idk

Revision ID: 1e8d03086008
Revises: 5337862c7514
Create Date: 2024-12-03 20:30:56.164253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8d03086008'
down_revision = '5337862c7514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('detailed_description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('detailed_description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
